; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:Production_Hardware_WROOM]
platform = espressif32
board = denky32
framework = arduino
lib_deps = 
	Wire
	bakercp/PacketSerial@^1.4.0
	robtillaart/CRC@^1.0.3
	fastled/FastLED@^3.9.2
	madhephaestus/ESP32Servo@^3.0.5
	jonniezg/EWMA@^1.0.2
build_flags = 
	-D DEBUG_MODE=false
monitor_speed = 115200

[env:DEBUG_WROOM]
platform = espressif32
board = denky32
framework = arduino
lib_deps = 
	Wire
	bakercp/PacketSerial@^1.4.0
	robtillaart/CRC@^1.0.3
	fastled/FastLED@^3.9.2
	madhephaestus/ESP32Servo@^3.0.5
	jonniezg/EWMA@^1.0.2
build_flags = 
	-D DEBUG_MODE=true
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_type = debug

[env:S2_Mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
lib_deps = 
	Wire
	bakercp/PacketSerial@^1.4.0
	robtillaart/CRC@^1.0.3
	fastled/FastLED@^3.9.2
	madhephaestus/ESP32Servo@^3.0.5
	jonniezg/EWMA@^1.0.2
build_flags = 
	-D DEBUG_MODE=true
monitor_speed = 115200

[env:nano_every]
platform = atmelmegaavr
board = nano_every
framework = arduino
lib_deps = 
	arduino-libraries/Servo@^1.2.2
	Wire
	bakercp/PacketSerial@^1.4.0
	robtillaart/CRC@^1.0.3
	fastled/FastLED@^3.9.2
	jonniezg/EWMA@^1.0.2
build_flags = 
	-D DEBUG_MODE=true
monitor_speed = 115200
